# Generated by Django 3.2.25 on 2025-02-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_blockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
