# Generated by Django 3.2.25 on 2025-02-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_coursemodel_course_thumbnail'),
        ('Student', '0002_remove_feedbackmodel_feedback_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_for',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Teacher.coursemodel'),
        ),
    ]
