# Generated by Django 3.2.25 on 2025-02-11 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_coursemodel_course_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0003_feedbackmodel_feedback_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.coursemodel')),
                ('enroll_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
